# -*- coding: utf-8 -*-
"""if-elif-else_statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5_4zzY2-zJbhsS9eUJriYEliWCmtm8c

🧩 elif Statement in Python
📘 What is elif?

The elif statement (short for “else if”) lets you check multiple conditions — one after another — and execute the block that matches first.

It’s used when you have more than two possibilities to handle.

🧠 Syntax

if condition1:
   
    # Code runs if condition1 is True
elif condition2:
    
    # Code runs if condition2 is True
elif condition3:
    # Code runs if condition3 is True
else:
    # Code runs if all above conditions are False

✅ Only one block executes, even if multiple conditions are true —
Python stops checking once it finds the first True condition.
"""

# 💡 Example 1: Grading System
marks = int(input("Enter your marks: "))

if marks >= 90:
    print("Grade: A+")
elif marks >= 80:
    print("Grade: A")
elif marks >= 70:
    print("Grade: B")
elif marks >= 60:
    print("Grade: C")
else:
    print("Grade: Fail")

# 💡 Example 2: Temperature Checker
temp = int(input("Enter temperature in °C: "))

if temp > 35:
    print("It's very hot ☀️")
elif temp > 25:
    print("It's warm 🌤️")
elif temp > 15:
    print("It's pleasant 🌸")
elif temp > 5:
    print("It's cool 🍃")
else:
    print("It's cold ❄️")

# 💡 Example 3: Day Number to Day Name
day = int(input("Enter day number (1-7): "))

if day == 1:
    print("Monday")
elif day == 2:
    print("Tuesday")
elif day == 3:
    print("Wednesday")
elif day == 4:
    print("Thursday")
elif day == 5:
    print("Friday")
elif day == 6:
    print("Saturday")
elif day == 7:
    print("Sunday")
else:
    print("Invalid day number!")

# 💡 Example 4: Movie Ticket Pricing by Age
age = int(input("Enter your age: "))

if age <= 5:
    print("Free entry for toddlers 👶")
elif age <= 12:
    print("Child ticket: ₹100 🎟️")
elif age <= 60:
    print("Adult ticket: ₹200 🎬")
else:
    print("Senior citizen ticket: ₹150 👴👵")

# 💡 Example 5: Nested Elif for BMI (Weight Category)
bmi = float(input("Enter your BMI: "))

if bmi < 18.5:
    print("Underweight")
elif 18.5 <= bmi < 24.9:
    print("Normal weight")
elif 25 <= bmi < 29.9:
    print("Overweight")
else:
    print("Obese")

"""🌟 Key Takeaways

if-elif-else is used when multiple conditions need checking.

Only one block executes — the first True one.

else is optional, but recommended for a fallback case.

Helps make programs logical and readable.
"""