# -*- coding: utf-8 -*-
"""if-else_statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvAIQNIc7zmdogaTUzCJaBH_csIbtBqw

📘 What is an if-else Statement?

The if-else statement helps your program make decisions.

The if block runs only when a given condition is True.

If the condition is False, then the else block runs instead.

In short:
👉 If something is true, do this… otherwise, do that.

🧩 Syntax

if condition:
   
    # Code to run if condition is True
else:
   
    # Code to run if condition is False

✅ Rules:

The condition must return either True or False.

The else block is optional but used for alternative actions.

Python uses indentation (spaces) to define code blocks.
"""

# 💡 Example 1: Positive or Negative Number
num = int(input("Enter a number: "))

if num >= 0:
    print("Positive number")
else:
    print("Negative number")

"""👉 Here, if the number is greater than or equal to 0, the first block runs.
Otherwise, the else part runs.
"""

# 💡 Example 2: Even or Odd
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

# 💡 Example 3: Voting Eligibility
age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

# 💡 Example 4: Pass or Fail
marks = int(input("Enter your marks: "))

if marks >= 40:
    print("Pass")
else:
    print("Fail")

# 💡 Example 5: Check Login Credentials
username = input("Enter your username: ")
password = input("Enter your password: ")

if username == "admin" and password == "password123":
    print("Login successful")
else:
    print("Invalid username or password")