# -*- coding: utf-8 -*-
"""if satatement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j814PFCp3RtEGoVZ6-_qJoyrDwWGPf48

🧠 What is an if Statement?

The if statement is used to make decisions in your program.
It checks whether a condition is true — and if it is, the code inside the if block runs.
If the condition is false, the code is skipped.

👉 Note:

The condition must return either True or False.

The code under if must be indented (usually 4 spaces).

Python uses indentation (not curly braces {}) to define code blocks.
"""

age = 18

if age >= 18:
    print("You are eligible to vote.")