# -*- coding: utf-8 -*-
"""Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UclvzM51y87XFoJ8Ueea_c6OjtJpa7ai

🔁 Loops in Python

Loops are used to execute a block of code multiple times until a certain condition is met.

Python provides two main types of loops:

for loop

while loop

🧠 1. for loop

The for loop is used to iterate over a sequence (like a list, tuple, string, or range).

🧩 Syntax:

 for variable in sequence:
   
    # block of code
"""

# ✅ Example 1: Printing Numbers 1 to 5
for i in range(1, 6):
    print(i)

# ✅ Example 2: Iterating Over a List
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# ✅ Example 3: Printing Characters in a String
for char in "Python":
    print(char)

# ✅ Example 4: Using range() Function
for i in range(5):  # 0 to 4
    print("Iteration:", i)

"""🧠 2. while loop

The while loop keeps running as long as the condition is True.

🧩 Syntax:

while condition:
    
    # block of code
"""

# ✅ Example 1: Print Numbers 1 to 5
count = 1
while count <= 5:
    print(count)
    count += 1

# ✅ Example 2: Countdown
countdown = 5
while countdown > 0:
    print(countdown)
    countdown -= 1

"""🧩 Using break and continue with Loops

🔸 break Statement

break is used to exit the loop immediately, even if the condition is still true.
"""

for i in range(1, 10):
    if i == 6:
        break
    print(i)

"""🔸 continue Statement

continue is used to skip the current iteration and move to the next one.
"""

for i in range(1, 6):
    if i == 3:
        continue
    print(i)