# -*- coding: utf-8 -*-
"""Nested-if_statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rO3akY_p4Vx9uXi_TlJXjkvgLHMick_o

🧩 Nested If Statement

A nested if statement means one if statement inside another.
It is used when you need to check multiple conditions that depend on each other.

🧠 Syntax:

if condition1:
    
    if condition2:
        # Executes when both condition1 and condition2 are True
        statement
    else:
        # Executes when condition1 is True but condition2 is False
        statement
else:
   
    # Executes when condition1 is False
    statement
"""

# ✅ Example 1: Checking Age and Citizenship
age = 20
citizen = "India"

if age >= 18:
    print("You are an adult.")
    if citizen == "India":
        print("You can vote in India.")
    else:
        print("You are not an Indian citizen.")
else:
    print("You are not an adult yet.")

# ✅ Example 2: Grade Classification
marks = 85

if marks >= 40:
    print("You passed the exam.")
    if marks >= 75:
        print("You got distinction!")
    elif marks >= 60:
        print("You got first class.")
    else:
        print("You got second class.")
else:
    print("You failed the exam.")

# ✅ Example 3: Number Check (Positive, Negative, Even/Odd)
num = 8

if num >= 0:
    print("Number is positive.")
    if num % 2 == 0:
        print("It is even.")
    else:
        print("It is odd.")
else:
    print("Number is negative.")